In [1]:
import numpy as np

In [2]:
# The game begins with two tiles already in the grid, having a value of either 2 or 4
def generate_board():
  A = np.zeros(shape=(4, 4))
  indices = np.random.choice(np.arange(16), size=2, replace=False)
  # TODO Randomly choose either 2 or 4
  A[indices // 4, indices % 4] = 2
  return A

# TODO Probably the bottleneck. Can we optimize this?
def process_row(row):
  # Avoid infinite while loop
  if np.all(row == 0):
    return
  # Look for matches, combine them if found
  for col in range(len(row) - 1):
    if row[col] == row[col + 1]:
      row[col] *= 2
      row[col + 1] = 0
  # Cycle so that no 0s remain on the appropriate side
  while row[0] == 0:
    row[:-1] = row[1:]
    row[-1] = 0

# Compute next board state for each move
def make_move(board, move):
  for i in range(4):
    if move == 'l':
      process_row(board[i, :])
    elif move == 'u':
      process_row(board[:, i])
    elif move == 'r':
      process_row(np.flip(board[i, :]))
    elif move == 'd':
      process_row(np.flip(board[:, i]))

  # TODO Need to make another tile be generated
  zero_coords = np.where(board == 0)
  num_zero = len(zero_coords[0])
  if num_zero > 0:
    new = np.random.randint(num_zero)
    board[zero_coords[0][new], zero_coords[1][new]] = 2

  print(move)
  print(board)

In [3]:
def terminal_value(board):
  # return np.sum(board)
  return np.sum(board) / np.sum(board != 0)

def max_recurser(board, moves=[], depth=3):
  if depth == 0 or np.all(board != 0):
    return terminal_value(board)
  else:
    max_seen = 0
    for move in ['l', 'u', 'r', 'd']:
      new_board = board
      make_move(new_board, move)
      max_seen = max(max_seen, max_recurser(new_board, moves + [move], depth - 1))
    return max_seen

In [4]:
A = generate_board()
print(A)
max_recurser(A, depth=1000)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 2. 0.]]
l
[[0. 0. 0. 2.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [2. 0. 0. 0.]]
l
[[2. 0. 2. 0.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [2. 0. 0. 0.]]
l
[[2. 0. 2. 0.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [2. 0. 0. 2.]]
l
[[2. 0. 2. 0.]
 [0. 0. 2. 0.]
 [2. 0. 0. 0.]
 [2. 0. 0. 2.]]
l
[[2. 0. 2. 0.]
 [2. 0. 0. 0.]
 [2. 0. 2. 0.]
 [2. 0. 0. 2.]]
l
[[2. 0. 2. 0.]
 [2. 0. 2. 0.]
 [2. 0. 2. 0.]
 [2. 0. 0. 2.]]
l
[[2. 0. 2. 0.]
 [2. 2. 2. 0.]
 [2. 0. 2. 0.]
 [2. 0. 0. 2.]]
l
[[2. 0. 2. 0.]
 [4. 0. 2. 2.]
 [2. 0. 2. 0.]
 [2. 0. 0. 2.]]
l
[[2. 2. 2. 0.]
 [4. 0. 4. 0.]
 [2. 0. 2. 0.]
 [2. 0. 0. 2.]]
l
[[4. 2. 2. 0.]
 [4. 0. 4. 0.]
 [2. 0. 2. 0.]
 [2. 0. 0. 2.]]
l
[[4. 4. 0. 0.]
 [4. 0. 4. 0.]
 [2. 0. 2. 2.]
 [2. 0. 0. 2.]]
l
[[8. 0. 0. 0.]
 [4. 0. 4. 2.]
 [2. 0. 4. 0.]
 [2. 0. 0. 2.]]
l
[[8. 0. 0. 2.]
 [4. 0. 4. 2.]
 [2. 0. 4. 0.]
 [2. 0. 0. 2.]]
l
[[8. 2. 0. 2.]
 [4. 0. 4. 2.]
 [2. 0. 4. 0.]
 [2. 0. 0. 2.]]
l
[[8. 2. 2. 2.]
 [4. 0. 4. 2.]
 [2. 0. 4. 0.]
 [2. 0. 0.

10.875